//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask.ModelsFromDB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Equipment
    {
        [Display(Name = "ИД Оборудования")]
        public int IdEquipment { get; set; }
        [Display(Name = "ИД Брэнд")]
        public int IdBrand { get; set; }
        [Display(Name = "ИД Инструмент")]
        public int IdToolType { get; set; }
        [Display(Name = "Описание")]
        public string Description { get; set; }
        [Display(Name = "Цена")]
        public double Price { get; set; }
    }
}
