//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask.ModelsFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolType
    {
        public int IdTool { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
